### PR TITLE
added prettier config

### PR DESCRIPTION
**Pull request by bdbch**

### CODE REVIEW

**Comment by howardchung** [comment]
Thanks for the PR!  I was actually hoping to use prettier with as close as zero-config as possible (see the prettier command in package.json). single-quote is the only thing I'm changing.

Are any of these rules something you'd strongly advocate for?

**Comment by bdbch** [comment]
The reason for a stricter prettier config would be that for example my VS Code autoformats documents on changes so I would break a lot of formatting done by someone else - and vice versa.

I think everyone using the same formatting rules would be a good start to avoid formatting issues (specially since prettier does it all for us).

**Comment by howardchung** [comment]
Does VSCode format according to the prettierrc or according to its own rules? Typically I just run `npm run prettier` from time to time to clean up formatting issues.

Also it looks like the bulk of these changes are trailing commas. Can we change that to "es5", the prettier default?

**Comment by bdbch** [comment]
@howardchung sure we can change that.

It depends, usually the most people install Prettier as a VS Code plugin and use it as the default formatter for almost everything js/ts related.

How about we add a precommit hook that runs prettier automatically so even if someone is not using a prettier plugin it gets commited formatted correctly?

**Comment by howardchung** [comment]
Let's try that.

I haven't really been a fan of the precommit hook in the odota/web code since it takes a while to run, but if it's annoying we can turn it off.

**Pull request merged**
